### ISSUE TITLE
Getting suspention from heroku

### ISSUE THREAD

**Issue by abishikth-jos** [kalanakt/All-Url-Uploader#16]
It have been noticed that I am getting suspention from heroku... On doing any url uploading tasks... While uploading (eg: Zee5 link etc.. )

**Comment by kalanakt** [comment]
working on that 

- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by kalanakt** [comment]
## To prevent:

- Try Not To Upload Copyright media.
- Avoid using [temporary mails](https://temp-mail.org/) to sign up for Heroku.
- Avoid regenerating of heroku api.
- Avoid using new emails to sign up
- Avoid using vpn or ad blocker
- Avoid controlling ( like shutting down, restarting, setting/editing of Heroku config vars, etc... ) apps much more. Instead, you can use in-bot commands.

## To solve:

- Use old accounts if you already signed with others.
- Try [transfering app](https://devcenter.heroku.com/articles/transferring-apps) from the old account to the new.
- [Reset the password](https://help.heroku.com/N3FIQBW1/how-do-i-reset-my-heroku-password) of the account.
- Control Heroku actions with the commands instead of controlling from Heroku.
- Try using another browser

These are the steps to prevent and solve issues.
There are no official tips/tricks but it's tested and there is a chance to work.
If that's still suspending, Then please write [support@heroku.com](mailto:support@heroku.com)

Thank You!

[Copied...](https://github.com/TOXIC-DEVIL/Leon/issues/31)

**Comment by samucamg** [comment]
My account was suspended even before I uploaded a single file.
